### ISSUE TITLE
Fixing broken HW #1

### ISSUE THREAD

**Issue by max9001** [UC-Irvine-CS175/final-project-saddleback#4]
### Current status

- augmentation fails
- dataset fails
- utils works, but we used Jacob's.

### Todo

- fix current errors
- replace Jacob's file with my own and fix any errors

### Assignees

- Max
- Jacob/Cam/Jasper if available and not fixed by sunday

**Comment by max9001** [comment]
augmentation and dataset working. Utils are not.

**Comment by max9001** [comment]
![Screenshot from 2023-05-21 11-38-36](https://github.com/UC-Irvine-CS175/final-project-saddleback/assets/111012399/7cd4b0c2-84d8-4899-9f73-73cb69f9c5d9)
I have found the sizes of the subsetsin the `data_utils` is wrong because it is building off the previous subset. I wonder why...

**Comment by max9001** [comment]
![Screenshot from 2023-05-21 12-25-31](https://github.com/UC-Irvine-CS175/final-project-saddleback/assets/111012399/deeeee73-6ed5-4298-9e3f-d5b0ecc8ba8a)
replaced with `==` and succeeded

**Comment by jasperdoan** [comment]
LGTM! Good job
![1wn](https://github.com/UC-Irvine-CS175/final-project-saddleback/assets/49565505/af6cceaa-287e-4e98-92e2-932b677dcb4e)

**Comment by max9001** [comment]
![giphy](https://github.com/UC-Irvine-CS175/final-project-saddleback/assets/111012399/5f98e048-726d-429c-a591-4515584ab758)
