### ISSUE TITLE
Change team icon to saddleback bobcat or something

### ISSUE THREAD

**Issue by max9001** [UC-Irvine-CS175/final-project-saddleback#6]
![cooltext436082979867047](https://github.com/UC-Irvine-CS175/final-project-saddleback/assets/111012399/d37ce15c-7c2f-45f5-a8f6-c59c1c738543)

**Comment by CakeJamble** [comment]
![image](https://github.com/UC-Irvine-CS175/final-project-saddleback/assets/104522681/34f9086f-e3ae-438c-92a6-8fd2612aa3a2)
